### ISSUE TITLE
access tickets

### ISSUE THREAD

**Issue by michielbdejong** [solid/web-access-control-spec#44]
As discussed in https://github.com/inrupt/websockets-pubsub/issues/2#issuecomment-489344939 the obvious way to pass a webid-oidc token to a websocket server (namely, same as for the WAC-LDP interface, wrap it into a bearer token in the `Authorization` header) is not possible when opening a WebSocket from the browser. I looked around for alternatives of how to give a WebSocket server a webid-oidc token from the browser, and options seem to be we can introduce a new scheme for this which the client should follow (that would be spec-breaking), or we can try to somehow configure the server in such a way that an authenticated client will open the WebSocket with proof of identity. One way to do that would be by setting a Cookie, but setting Cookies from an API is a bit ugly. So the other option would be to use a short-lived 'read capability' as the `Updates-Via` URL. So either the link from the `Updates-Via` header instructs the client to include their whole PoP token in the URL (but that's not best practice because of replay attacks), or the URL includes a short-lived proof of identity (much saner from a security perspective), which we can call an 'access ticket', and hopefully that ticket could also be a shorter string (although if that makes shared state between the wac-ldp server and the websockets-pubsub server necessary then the shortness of the string may not be worth it).

**Comment by michielbdejong** [comment]
@acoburn @jaxoncreed @dmitrizagidulin I put this topic on the agenda for https://www.w3.org/community/solid/wiki/Meetings#20190509_1600CEST, would be great to have you there for the discussion if you can make the time! :)

**Comment by acoburn** [comment]
@michielbdejong I have another meeting right at this time, but I may be able to join the Solid call late. I like the idea of a short-lived access token, but we'd want to consider the implications of adding that to every `OPTIONS` response (regardless of whether a client eventually opens a websocket connection). Doing so would make the `OPTIONS` request a little less idempotent, especially if these tickets are being stored in some type of database. This would also require some level of coordination between the HTTP nodes (assuming that there may be multiple such nodes) and the websocket node(s), which could be on entirely different servers. This is really only an issue for a distributed version of Solid, but I think it's an important consideration. Perhaps these "Access Tickets" should be generated by a `POST` request to some endpoint rather than just issuing an `OPTIONS` request?

**Comment by michielbdejong** [comment]
Right, and also I'm not sure whether clients will always send an `Authorization` header when doing an OPTIONS request? If not, then it's all not going to work anyway...

**Comment by RubenVerborgh** [comment]
Side-note, let's not put too into OPTIONS: https://www.mnot.net/blog/2012/10/29/NO_OPTIONS

**Comment by elf-pavlik** [comment]
I wonder if this belongs to WAC spec or Solid spec? Possibly this issue may need to get transferred to solid-spec repo.

In https://github.com/solid/solid-spec/issues/123 we again discussed Server-Sent Events which shouldn't have that issue.

**Comment by michielbdejong** [comment]
Yes sorry, this issue is indeed more about the [WebSockets-pubsub](https://github.com/solid/solid-spec/blob/master/api-websockets.md) spec, not about the WAC spec, continuing there ^

**Comment by elf-pavlik** [comment]
One of the admins could also use [Transferring an issue to another repository](https://help.github.com/en/articles/transferring-an-issue-to-another-repository) github feature.

**Comment by michielbdejong** [comment]
yeah, just discovered that feature today, too :)
